edwardtheharris/rsum

.gitignore
.travis.yml
defaults/main.yml
files/cv.yml
handlers/main.yml
meta/main.yml
molecule/default/create.yml
molecule/default/destroy.yml
molecule/default/molecule.yml
molecule/default/playbook.yml
molecule/default/requirements.yml
molecule/default/tests/test_default.py
tasks/main.yml
vars/main.yml

It passes lint.

---

files/rsum/cv.yml
files/rsum/rsum/home/models.py
files/rsum/rsum/home/views.py

Gonna start making models now.

Added skills. See #11.

---

files/rsum/cvs/abridged.yml
files/rsum/cvs/complete.yml
files/rsum/rsum/home/templates/home/sections/education.html
files/rsum/rsum/home/views.py

That displays all right.

---

files/rsum/rsum/home/templates/home/sections/contact.html

Displays with correct information.

---

files/rsum/rsum/home/schema/cv.py
files/rsum/rsum/home/schema/entry.py
files/rsum/rsum/home/schema/entryitem.py
files/rsum/rsum/home/schema/project.py
files/rsum/rsum/home/schema/projectitem.py
files/rsum/rsum/home/schema/section.py
files/rsum/rsum/home/schema/subsection.py
files/rsum/rsum/home/views.py

Passing PEP8

---

.travis.yml
files/rsum/rsum/home/schema/projectitem.py
files/rsum/rsum/rsum/settings.py
molecule/default/create.yml
molecule/default/molecule.yml
molecule/default/playbook.yml
molecule/default/requirements.yml
tasks/main.yml
vars/main.yml

Which requires a separate container.

Make it use PostgreSQL

---

.travis.yml
files/alex/docker-compose.yml
files/rsum/rsum/home/schema/subsection.py
molecule/default/molecule.yml
tasks/main.yml

And ideally deploy to production automatically.

Site should load with PostgreSQL

---

files/rsum/rsum/home/exam/cv.py
files/rsum/rsum/home/exam/entry.py
files/rsum/rsum/home/exam/entryitem.py
files/rsum/rsum/home/exam/project.py
files/rsum/rsum/home/exam/projectitem.py
files/rsum/rsum/home/exam/section.py
files/rsum/rsum/home/exam/subsection.py
files/rsum/rsum/home/schema/cv.py
files/rsum/rsum/home/schema/project.py
files/rsum/rsum/home/schema/projectitem.py
files/rsum/rsum/home/schema/section.py
files/rsum/rsum/home/templates/home/index.html
files/rsum/rsum/home/templates/home/sections/contact.html
files/rsum/rsum/home/templates/home/sections/education.html
files/rsum/rsum/home/templates/home/sections/experience.html
files/rsum/rsum/home/templates/home/sections/intro.html
files/rsum/rsum/home/templates/home/sections/summary.html
files/rsum/rsum/home/templates/home/sections/values.html
files/rsum/rsum/home/tests.py
files/rsum/rsum/home/views.py

Leaving only the infratest stuff to write.

Pass get tests for models.

---

files/rsum/rsum/home/schema/subsection.py
files/rsum/rsum/rsum/__init__.py
files/rsum/rsum/rsum/settings.py
molecule/default/tests/test_default.py

It's almost like there's a software engineer working on this.

All tests are good.

---

files/rsum/rsum/home/exam/cv.py

More for test. See #57.

---

README.md
files/rsum/cvs/alex/abridged.yml
files/rsum/cvs/alex/complete.yml
files/rsum/cvs/alex/engineer.yml

Update name to Alex.

---

files/rsum/rsum/home/templates/home/sections/experience.html

Though not as dramatically as once thought.

They got moved.

---

files/alex/angnx/Dockerfile
files/alex/angnx/p.yml
files/alex/angnx/r.yml
files/deploy.bash
files/rsum/cvs/alex/abridged.yml
files/rsum/cvs/alex/complete.yml
files/rsum/cvs/alex/engineer.yml
files/rsum/rsum/rsum/settings.py
files/supervisor/angnx.conf
molecule/default/molecule.yml
molecule/default/playbook.yml
molecule/default/requirements.yml
tasks/main.yml

Add NGNX build status.

---

files/deploy.bash
files/rsum/rsum/rsum/settings.py
molecule/default/create.yml
molecule/default/molecule.yml
tasks/db/mrsum.yml

Will it blend?

---

files/rsum/rsum/home/templates/home/sections/summary.html

It's probably nothing. . . 
Probably.

One commit, one issue. See #72.

---

files/rsum/cvs/alex/abridged.yml
files/rsum/cvs/alex/complete.yml
files/rsum/cvs/alex/engineer.yml

Alexitor has been replaced with Editor.

---

files/rsum/cvs/alex/abridged.yml
files/rsum/cvs/alex/complete.yml
files/rsum/cvs/alex/engineer.yml
files/rsum/rsum/home/templates/home/sections/summary.html

Includes running availability.

Added Calendly button for scheduling calls.

---

files/rsum/cvs/alex/abridged.yml
files/rsum/cvs/alex/complete.yml
files/rsum/cvs/alex/engineer.yml

Also solves the problem of uneven boxes.

Quotes for values.

---

files/rsum/cvs/jess/general.yml
files/rsum/rsum/home/export/word.py
files/rsum/rsum/home/schema/cv.py
files/rsum/rsum/home/templates/home/sections/summary.html
files/rsum/rsum/home/views.py
files/rsum/rsum/rsum/settings.py
files/rsum/rsum/rsum/urls.py

Reads cv_id and exports to docx.

Export CV for Jess as well.

---

files/rsum/cvs/alex/abridged.yml
files/rsum/cvs/alex/complete.yml
files/rsum/cvs/alex/engineer.yml
files/rsum/cvs/alex/talent-merchants.yml
tasks/main.yml
vars/main.yml

Also include update to enable functionality for python-docx.

Update to install python-docx correctly.

---

tasks/facts.yml
tasks/main.yml
vars/main.yml

To include all files in the cvs directory.

Load variables from file paths.

---

.travis.yml

Pass all the tests.

---

.gitignore
Dockerfile
readme.rst

Dockerfile was the last artifact.

---

readme.rst
rsum/home/tests/models/conftest.py
rsum/home/tests/models/test_profile.py
rsum/home/tests/models/test_secion.py
setup.cfg

Update. See #166.

---

rsum/home/export/layout.py
rsum/home/export/style.py
rsum/home/export/word.py

Fix method_lines error in word.py.

Closes #162.

---

rsum/home/export/contact.py
rsum/home/export/word.py

Split up files, adjust arguments.

Should solve complexity issues. Closes #164.

---

rsum/rsum/create.py

Adjust to use tempfile. See #186.

---

rsum/home/export/word.py

Define static method. See #187.

---

.travis.yml
container/Dockerfile
container/run
static/profiles/xander/complete.yml

Add deploy via dockerfile.

---

.requirements
Pipfile
Pipfile.lock
bin/Dockerfile
rsum/export/models.py
rsum/home/export/word.py
rsum/home/models/profile.py
rsum/home/templates/home/index.html
rsum/home/templates/home/sections/clients.html
rsum/home/templates/home/sections/education.html
rsum/home/templates/home/sections/experience.html
rsum/home/templates/home/sections/intro.html
rsum/home/templates/home/sections/summary.html
rsum/rsum/settings.py
static/profiles/xander/xander.yml

Serves from Amazon S3, fonts and all. Closes #214.

---

bin/Dockerfile

Fix branch. See #214.

---

bin/Dockerfile

Fix branch. See #173.

---

.circleci/config.yml

Add coverage for code climate.

---

rsum/export/sections/skills.py
rsum/export/sections/summary.py
rsum/home/templates/home/sections/summary.html

Drops picture from summary.

---

static/profiles/xander/xander.yml

Fix titles.

---

bin/Dockerfile
rsum/home/models/skills.py
rsum/home/templates/thecraiglist/index.html
static/profiles/xander/xander.yml

Replace programmer with engineer. See #281

---

static/profiles/dev/dev.yml
static/profiles/xander/xander.yml

Fix for Noah Lee's catches.

---

readme.md
rsum/export/sections/education.py
rsum/export/sections/skills.py
static/profiles/xander/xander.yml

Fix typo. See #289.

---

doc/source/index.rst
rsum/home/templates/home/index.html
rsum/home/views.py
rsum/rsum/settings.py

Since this gets traffic, unlike the company website.

Add google analytics.

---

rsum/rsum/settings.py

#241 
Finally got the AWS turned off. I really need a job.

Adjust key location. See #241.

---

readme.md

CircleCI is broken. See #241.

---

rsum/home/templates/home/index.html

Set link for simple line icons. See #241.

---

rsum/export/models.py
rsum/export/sections/contact.py
rsum/export/sections/experience.py
rsum/export/sections/skills.py
rsum/export/sections/summary.py
rsum/export/tools/style.py
rsum/rsum/settings.py
static/profiles/xander/xander.yml

Updates for Formatting. #280

---

.circleci/config.yml
.travis.yml
bin/Dockerfile
bin/travis

Fix travis build. See #280.

---

.circleci/config.yml
Pipfile.lock
bin/create

Deploy to Heroku.

---

rsum/export/sections/experience.py
rsum/export/sections/summary.py

Fix export with graphics. 

---

readme.md
rsum/export/tests/conftest.py

Fixed. See #312.
